services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expenses_user
      POSTGRES_PASSWORD: "expenses_app!"
      POSTGRES_DB: expenses_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: