services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: '/migration /app/sql'

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expenses_user
      POSTGRES_PASSWORD: "expenses_app!"
      POSTGRES_DB: expenses_db
    volumes:
      - db_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80" # Port mapping for pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Default pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin       # Default pgAdmin login password
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: