name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with commit hash and latest tags
        run: |
          COMMIT_HASH=${{ github.sha }}
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          
          # Build the image
          docker build -t $IMAGE_NAME:${COMMIT_HASH} -t $IMAGE_NAME:latest .

          # Push both tags
          docker push $IMAGE_NAME:${COMMIT_HASH}
          docker push $IMAGE_NAME:latest

      # - name: Notify VPS via Webhook
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #     -d '{"status":"success","image":"my-docker-repo/my-app:latest"}' \
      #     ${{ secrets.WEBHOOK_URL }}